services:
  - type: web
    name: virtual-museum
    env: node
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true